// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using minhaprimeiraapi.Data;

#nullable disable

namespace minhaprimeiraapi.Migrations
{
    [DbContext(typeof(ContextTaskSystemDB))]
    [Migration("20240614051136_KarapinhaDB")]
    partial class KarapinhaDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("minhaprimeiraapi.Model.AppointmentServicesModel", b =>
                {
                    b.Property<int>("appointmentServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointmentServiceId"));

                    b.Property<int>("appointmentId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("serviceId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("appointmentServiceId");

                    b.ToTable("AppointmentServices");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.AppointmentsModel", b =>
                {
                    b.Property<int>("appointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("appointmentId"));

                    b.Property<DateOnly>("date")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dateCreated")
                        .HasMaxLength(80)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateModified")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<int>("professionalId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("serviceId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("status_appointment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("time")
                        .HasColumnType("TIME");

                    b.Property<decimal>("totalPrice")
                        .HasMaxLength(15)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("userId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("appointmentId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.EmailsModel", b =>
                {
                    b.Property<int>("emailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emailId"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateSent")
                        .HasColumnType("datetime");

                    b.Property<string>("statusEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("emailId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.ProfessionalModel", b =>
                {
                    b.Property<int>("professionalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("professionalsId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("bi")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("dateCreated")
                        .HasMaxLength(80)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateModified")
                        .HasMaxLength(80)
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("photo")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("workingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("professionalsId");

                    b.ToTable("Professional");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.ServiceModel", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<string>("category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("dateModified")
                        .HasColumnType("datetime");

                    b.Property<decimal>("price")
                        .HasMaxLength(15)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("serviceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("serviceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.UserModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("bi")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("dateCreated")
                        .HasMaxLength(80)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateModified")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("isActive")
                        .HasMaxLength(5)
                        .HasColumnType("bit");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("usertype")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("minhaprimeiraapi.Model.UserProfileModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("additionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("photo")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("userId");

                    b.ToTable("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
